server:
  port: ${PORT:8070}
  api:
#  tomcat:
#    threads:
#      max: 2
  address: localhost # be carefull for docker env it might fail
spring:
  application:
    name: InventoryService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inventory
#      username: user
#      password: password
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update     # Database schema update strategy (if using JPA)
    show-sql: false         # Show SQL queries (if using JPA)

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]


service-discovery:
  endpoint: http://localhost:8005/discovery
  period: 5 # seconds
  tag: inventory

logging:
  level:
    root: info