version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit_network

  rabbitmq_config:
    image: rabbitmq:management
    container_name: "rabbitmq_config"
    depends_on:
      - rabbitmq
    volumes: 
      - ./config/run.sh:/app/init.sh
    command: sh -c "sleep 10 && chmod +x /app/init.sh && /app/init.sh"
    networks:
      - rabbit_network
      
networks:
  rabbit_network:
    name: rabbit_network
