server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: bid
  static_configs:
  - targets:
    - localhost
    labels:
      job: bidlogs
      __path__: /app/logs/pad/bid/*/*log

- job_name: gateway
  static_configs:
  - targets:
    - localhost
    labels:
      job: gatewaylogs
      __path__: /app/logs/pad/gateway/*log

- job_name: service_discovery
  static_configs:
  - targets:
    - localhost
    labels:
      job: service_discovery
      __path__: /app/logs/pad/service_discovery/*log

- job_name: inventory
  static_configs:
  - targets:
    - localhost
    labels:
      job: inventory
      __path__: /app/logs/pad/inventory/*/*log

- job_name: orchestrator
  static_configs:
  - targets:
    - localhost
    labels:
      job: orchestrator
      __path__: /app/logs/pad/orchestrator/*log