apiVersion: v1
kind: Service
metadata:
  name: bid-cassandra
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: inventory-cassandra
#spec:
#  selector:
#    app: cassandra
#  ports:
#    - protocol: TCP
#      port: 9042
#      targetPort: 9042
