apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  clusterIP: None
  ports:
    - port: 9042

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:latest
          env:
            - name: CASSANDRA_USER
              valueFrom:
                configMapKeyRef:
                  name: cassandra-config-map
                  key: cassandra-user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-secrets
                  key: cassandra-password
#            - name: CASSANDRA_CLUSTER_NAME
#              value: your_cassandra_cluster_name
          ports:
            - containerPort: 9042
          resources:
            limits:
              memory: "1Gi"